### PR TITLE
Add options for compiling to OSX

### PR DESCRIPTION
**Pull request by sbritorodr**
# OSX compilation options:
## Before merging:
This code compiles a ironwail OSX executable but doesn't run on OSX due to needing OpenGL 4.3 to run (Ironwail says I'm stuck in OpenGL 2. I think).
This PR purpose is to make it avaliable in the future by using a translation layer between OGL 4.3 to Metal (Vulkan alternative for OSX). Maybe looking for MoltenGL, ANGLE, Zink, OpenGL to Metal Adapter, gfx-portability...
Those options do not support OpenGL 4.3 _yet_ but I'm sure it will do in the future.

## Changes to this PR
- Added Makefile.darwin for compiling to OSX
- Added .gitignore for ".DS_Store" garbage files created by OSX
- Removed old code for MacOS that broke compilation for MacOS. For some reason, in [Quake/main_sdl.c](https://github.com/andrei-drexler/ironwail/blob/5fab9da81d403c3735d2cdfc9ee0aa95b498814e/Quake/main_sdl.c#L121) there is a `#define main SDL_main` line that only runs if it's compiled in OSX. However, this line of code gives me this error at linking: 

```
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: _m_main_mods, _SDL_main , _m_main_cursor )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Removing this allows me to compile the proyect without issues. Maybe is just a Quakespasm old code?

## How to compile (Or at least what I did)
Add to /Library/Frameworks/ these frameworks:
`IOKit CoreGraphics OpenGl CoreFoundation SDL2`

I found it in /System/Library/Frameworks but I'm not sure if this comes with xcode-select installed.

Run this command inside Quake/
`make -j$(nproc)`
Or manually select your avaliable threads and replace it with `$(nproc)`

### CODE REVIEW

**Comment by garoto** [comment]
> make -f Makefile.darwin -j4
>
>Where -j4 means to compile using 4 threads, so it depends on your processor CPU threads.

Learned this not too long ago: `make -j$(nproc)`

`nproc` is part of GNU's coreutils.

**Comment by sbritorodr** [comment]
I'm trying to do the translation layer since my main objective is not to modify any source files but Makefiles in order to not bother the devs trying to maintain a platform he/she doesn't have.
I will leave this for now due to lack of free time right now. I will leave some useful threads I've found:
- [How to use OpenGL on Zink, Mesa, MoltenVK, and macOS · Kronos Forum](https://community.khronos.org/t/how-to-use-opengl-on-zink-mesa-moltenvk-and-macos/108160)

**Comment by Calinou** [comment]
MoltenVK cannot translate OpenGL to Metal directly (unless you use Zink as an intermediary), and MoltenGL is limited to OpenGL ES 3.0 (and is also proprietary).

**Comment by sbritorodr** [comment]
@Calinou Thanks a lot for the info. I am researching about this and I am aware of using Zink as an intermediary. In the Kronos Forum link I've posted the OP is trying to do this.

I am aware of the performance impact, it's just that I don't know if this impact is relevant enough to be slower than Quakespasm or vkQuake. Also I'm doing it just for fun too.

But yes, OSX is a very awful platform to port games either way. Completely removing OpenGL and Vulkan in favor of Metal sound a bit of Apple whim just to use MoltenVK either way.

**Pull request closed without merging**
