### PR TITLE
Up limits on alias model tris and vertices

### LINKED ISSUE #352: Maroooned by MFX+Orl won't load - model w/ too many vertices
image

According to Orl, the map/assets should work in FTE and QSS; supposedly it should work in IW as well minus some 3d skybox feature QSS and FTE have.

The files can be found [here](https://www.slipseer.com/index.php?resources/marooned.412/) (Requires [Mjolnir](https://www.slipseer.com/index.php?resources/quake-mj%C3%B6lnir.243/))

### PR DESCRIPTION
**Pull request by 4LT**
Doubles the limit on alias model triangles, and doubles the limit on alias model vertices (to nearest power of 2).

Resolves #352

### CODE REVIEW

**Comment by andrei-drexler** [comment]
@sezero @j0zzz I think ideally these limits would be increased in QS and JoeQuake as well, to avoid incompatibilities between engines.

**Comment by 4LT** [comment]
To be quite honest, I don't know why there's a per-model vertex and triangle limit, seems to me there should just be a global limit.  Since models are pre-cached as opposed to loaded at runtime, there shouldn't be a negative performance impact from using a growable data structure

**Comment by andrei-drexler** [comment]
Since it doesn't look like the new limits will be adopted by other engines, I went with a different approach in https://github.com/andrei-drexler/ironwail/commit/df8f9261bfe94bcfe31d38dd678c6888f1c98325 - the triangle/vertex limits are gone, and the code just emits QS compatibility warnings for developers instead. The frame limit is still there for now, though.

**Comment by mhQuake** [comment]
I don't think the old limits are relevant anyway, other than if compatibility with software Quake and the old meshing code is felt important. Other engines should likewise push to remove them.

This is aside from the frame limit, which is protocol-dependent, of course.

**Pull request closed without merging**
