### PR TITLE
Add support for building with CMake

### PR DESCRIPTION
**Pull request by skalleAnka**
This will make it possible to use CMake for building.

On Linux most IDEs/editors CMake seems to be the default option these days. On Windows it is the best option when using VSCode and is also supported natively by Visual Studio as an alternative to project files.

On linux this will find SDL, CURL and the codec packages automatically if they are installed. On Windows it uses the bundled libraries. I think it should be possible to reconfigure on Windows to use packages from some other location but I have not tested that.

It should be largely self-maintaining: If new source files are added to (or removed from) the Quake folder, it will pick them up without modification of the scripts.

I have tested this with Debian 12 Linux (GCC and Clang) and with Visual Studio 2022 and it seems to work.

### CODE REVIEW

**Comment by skalleAnka** [comment]
Now also tested with MINGW - had some trouble with the SDL2main library but it should be sorted now.

**Comment by skalleAnka** [comment]
Modified it to extract version number from quakedef.h, making it even more maintenance free.

**Comment by skalleAnka** [comment]
Updated PR to remove CD support as in master

**Comment by andrei-drexler** [comment]
Added in https://github.com/andrei-drexler/ironwail/commit/a8de85b232689386545b62443b100a1fe2d2c2e0, thank you!

**Pull request merged**
